[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_loot_program = "B1WrZv1rwvX38iCXKsW2Eh98G2oySWzfBssG9XjVhN1V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
